version: 0.0
os: linux
files:
  - source: deploy/cp-organisations-service.conf
    destination: /etc/init/
  - source: /
    destination: /opt/zen/cp-organisations-service

permissions:
  - object: /opt/zen/cp-organisations-service
    owner: ubuntu
    group: ubuntu
  
hooks:
  ApplicationStop:
    - location: deploy/stop-server.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: deploy/start-server.sh
      timeout: 300
      runas: root

  

