#!/bin/bash

# variables
id=$1
github=$2
entrypoint=$3

# create Dockerfile
echo "creating Dockerfile..."
rm Dockerfile &> /dev/null
touch Dockerfile &> /dev/null
echo "FROM python:3
RUN apt-get update && apt-get install unzip
RUN git clone $github
WORKDIR /$id
RUN unzip *.zip -d projectFiles
WORKDIR /$id/projectFiles
CMD [ \"python\", \"./$entrypoint\" ]" >> Dockerfile

# build docker image
echo "building docker image..."
docker build -t project . &> /dev/null

# run the project
echo "running project..."
echo ""
docker run -i project

# remove the image
echo ""
echo "END OF PROJECT OUTPUT"
docker rmi -f project &> /dev/null
rm Dockerfile &> /dev/null